#pragma once

#include <fstream>
#include <iostream>
#include <sstream>
#include <vector>
#include <functional>
#include <string>
#include "mfem.hpp"
#include "DGOperator.hpp"
#include "BasicOperations.hpp"
#include "ModalBasis.hpp"
#include "EntropyFilter.hpp"
#include "BdrFaceIntegrator.hpp"
#include "WallBdrFaceIntegrator.hpp"
#include "FixedStateBdrFaceIntegrator.hpp"
#include "OutletBdrFaceIntegrator.hpp"
#include "TimeDependentBdrFaceIntegrator.hpp"
#include "LaxFriedrichsFlux.hpp"
#include "DGODESolver.hpp"
#include "RK3SSPExplicitSolver.hpp"
#include "Physics.hpp"